[env:app]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
lib_deps = 
    pololu/VL53L0X
    waspinator/AccelStepper
build_src_filter = 
    +<common/>
    +<app/>


[env:test_sensor]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
lib_deps = 
    pololu/VL53L0X
    waspinator/AccelStepper
build_src_filter = 
    +<common/>
    +<tests/sensor>


[env:test_lift_motor]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
lib_deps = 
    pololu/VL53L0X
    waspinator/AccelStepper
build_src_filter = 
    +<common/>
    +<tests/lift_motor>


[env:test_limit_switch]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
lib_deps = 
    pololu/VL53L0X
    waspinator/AccelStepper
build_src_filter = 
    +<common/>
    +<tests/limit_switch>


[env:test_pusher_motor]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
lib_deps = 
    pololu/VL53L0X
    waspinator/AccelStepper
build_src_filter = 
    +<common/>
    +<tests/pusher_motor>
