[env:app]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
lib_deps = 
    pololu/VL53L0X
    waspinator/AccelStepper
build_src_filter = 
    +<common/>
    +<app/>


[env:test_sensor]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
lib_deps = 
    pololu/VL53L0X
    waspinator/AccelStepper
build_src_filter = 
    +<common/>
    +<tests/sensor>


[env:test_lift_motor]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
monitor_echo = yes
lib_deps = 
    pololu/VL53L0X
    waspinator/AccelStepper
build_src_filter = 
    +<common/>
    +<tests/lift_motor>


[env:test_limit_switch]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
lib_deps = 
    pololu/VL53L0X
    waspinator/AccelStepper
build_src_filter = 
    +<common/>
    +<tests/limit_switch>


[env:test_pusher_motor]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
monitor_echo = yes
lib_deps = 
    pololu/VL53L0X
    waspinator/AccelStepper
build_src_filter = 
    +<common/>
    +<tests/pusher_motor>


[env:test_esp8266]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
monitor_echo = yes
build_src_filter =
    +<tests/esp8266>


[env:test_esp8266_nodemcu]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
build_src_filter =
    +<tests/esp8266_nodemcu>


[env:bridge_nodemcu]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
build_src_filter =
    +<bridge/>

